// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of AcceptEnterpriseMemberInvitation.
	/// </summary>
	public class AcceptEnterpriseMemberInvitationPayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The invitation that was accepted.
		/// </summary>
		public EnterpriseMemberInvitation Invitation { get; set; }

		/// <summary>
		/// A message confirming the result of accepting an unaffiliated member invitation.
		/// </summary>
		public string Message { get; set; }
	}
}
