// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of AccessUserNamespaceRepository.
	/// </summary>
	public class AccessUserNamespaceRepositoryPayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The time that repository access expires at
		/// </summary>
		public DateTimeOffset? ExpiresAt { get; set; }

		/// <summary>
		/// Humanized string of "The time that repository access expires at"
		/// <summary>
		public string ExpiresAtHumanized { get; set; }

		/// <summary>
		/// The repository that is temporarily accessible.
		/// </summary>
		public Repository Repository { get; set; }
	}
}
