// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of AccessUserNamespaceRepository
	/// </summary>
	public class AccessUserNamespaceRepositoryInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the enterprise owning the user namespace repository.
		/// </summary>
		public ID EnterpriseId { get; set; }

		/// <summary>
		/// The ID of the user namespace repository to access.
		/// </summary>
		public ID RepositoryId { get; set; }
	}
}
