// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

#nullable enable

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of AddAssigneesToAssignable
	/// </summary>
	public class AddAssigneesToAssignableInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string? ClientMutationId { get; set; }

		/// <summary>
		/// The id of the assignable object to add assignees to.
		/// </summary>
		public ID AssignableId { get; set; }

		/// <summary>
		/// The ids of actors (users or bots) to add as assignees.
		/// </summary>
		public List<ID> AssigneeIds { get; set; } = default!;

		/// <summary>
		/// Configuration for assigning Copilot to this issue.
		/// </summary>
		public AgentAssignmentInput? AgentAssignment { get; set; }
	}
}
