// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

#nullable enable

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of AddBlockedBy
	/// </summary>
	public class AddBlockedByInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string? ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the issue to be blocked.
		/// </summary>
		public ID IssueId { get; set; }

		/// <summary>
		/// The ID of the issue that blocks the given issue.
		/// </summary>
		public ID BlockingIssueId { get; set; }
	}
}
