// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of AddBlockedBy.
	/// </summary>
	public class AddBlockedByPayload
	{
		/// <summary>
		/// The issue that is blocking the given issue.
		/// </summary>
		public Issue BlockingIssue { get; set; }

		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The issue that is blocked.
		/// </summary>
		public Issue Issue { get; set; }
	}
}
