// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

#nullable enable

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of ArchivePullRequest
	/// </summary>
	public class ArchivePullRequestInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string? ClientMutationId { get; set; }

		/// <summary>
		/// The Node ID of the pull request to archive.
		/// </summary>
		public ID PullRequestId { get; set; }
	}
}
