// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

#nullable enable

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of CreateIssueFieldValue.
	/// </summary>
	public class CreateIssueFieldValuePayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string? ClientMutationId { get; set; }

		/// <summary>
		/// The issue object.
		/// </summary>
		public Issue? Issue { get; set; }

		/// <summary>
		/// The newly created issue field value.
		/// </summary>
		public IssueFieldValue? IssueFieldValue { get; set; }
	}
}
