// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

#nullable enable

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of CreateProjectV2StatusUpdate.
	/// </summary>
	public class CreateProjectV2StatusUpdatePayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string? ClientMutationId { get; set; }

		/// <summary>
		/// The status update updated in the project.
		/// </summary>
		public ProjectV2StatusUpdate? StatusUpdate { get; set; }
	}
}
