// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of CreateProjectV2IssueField
	/// </summary>
	public class CreateProjectV2IssueFieldInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the Project to create the field in.
		/// </summary>
		public ID ProjectId { get; set; }

		/// <summary>
		/// The ID of the IssueField to create the field for.
		/// </summary>
		public ID IssueFieldId { get; set; }
	}
}
