// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

#nullable enable

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of CreateIssue
	/// </summary>
	public class CreateIssueInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string? ClientMutationId { get; set; }

		/// <summary>
		/// The Node ID of the repository.
		/// </summary>
		public ID RepositoryId { get; set; }

		/// <summary>
		/// The title for the issue.
		/// </summary>
		public string Title { get; set; } = default!;

		/// <summary>
		/// The body for the issue description.
		/// </summary>
		public string? Body { get; set; }

		/// <summary>
		/// The Node ID of assignees for this issue.
		/// </summary>
		public List<ID>? AssigneeIds { get; set; }

		/// <summary>
		/// The Node ID of the milestone for this issue.
		/// </summary>
		public ID? MilestoneId { get; set; }

		/// <summary>
		/// An array of Node IDs of labels for this issue.
		/// </summary>
		public List<ID>? LabelIds { get; set; }

		/// <summary>
		/// An array of Node IDs for projects associated with this issue.
		/// </summary>
		public List<ID>? ProjectIds { get; set; }

		/// <summary>
		/// An array of Node IDs for Projects V2 associated with this issue.
		/// </summary>
		public List<ID>? ProjectV2Ids { get; set; }

		/// <summary>
		/// The name of an issue template in the repository, assigns labels and assignees from the template to the issue
		/// </summary>
		public string? IssueTemplate { get; set; }

		/// <summary>
		/// The Node ID of the issue type for this issue
		/// </summary>
		public ID? IssueTypeId { get; set; }

		/// <summary>
		/// The Node ID of the parent issue to add this new issue to
		/// </summary>
		public ID? ParentIssueId { get; set; }

		/// <summary>
		/// An array of issue fields to set on the issue during creation
		/// </summary>
		public List<IssueFieldCreateOrUpdateInput>? IssueFields { get; set; }

		/// <summary>
		/// Configuration for assigning Copilot to this issue.
		/// </summary>
		public AgentAssignmentInput? AgentAssignment { get; set; }
	}
}
