// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of CreateIssueType
	/// </summary>
	public class CreateIssueTypeInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID for the organization on which the issue type is created
		/// </summary>
		public ID OwnerId { get; set; }

		/// <summary>
		/// Whether or not the issue type is enabled on the org level
		/// </summary>
		public bool IsEnabled { get; set; }

		/// <summary>
		/// Name of the new issue type
		/// </summary>
		public string Name { get; set; }

		/// <summary>
		/// Description of the new issue type
		/// </summary>
		public string Description { get; set; }

		/// <summary>
		/// Color for the issue type
		/// </summary>
		public IssueTypeColor? Color { get; set; }
	}
}
