// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

#nullable enable

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of CreateProjectV2Field
	/// </summary>
	public class CreateProjectV2FieldInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string? ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the Project to create the field in.
		/// </summary>
		public ID ProjectId { get; set; }

		/// <summary>
		/// The data type of the field.
		/// </summary>
		public ProjectV2CustomFieldType DataType { get; set; }

		/// <summary>
		/// The name of the field.
		/// </summary>
		public string Name { get; set; } = default!;

		/// <summary>
		/// Options for a single select field. At least one value is required if data_type is SINGLE_SELECT
		/// </summary>
		public List<ProjectV2SingleSelectFieldOptionInput>? SingleSelectOptions { get; set; }

		/// <summary>
		/// Configuration for an iteration field.
		/// </summary>
		public ProjectV2IterationFieldConfigurationInput? IterationConfiguration { get; set; }
	}
}
