// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of CreateIssueField
	/// </summary>
	public class CreateIssueFieldInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the organization where the issue field will be created.
		/// </summary>
		public ID OwnerId { get; set; }

		/// <summary>
		/// The name of the issue field.
		/// </summary>
		public string Name { get; set; }

		/// <summary>
		/// A description of the issue field.
		/// </summary>
		public string Description { get; set; }

		/// <summary>
		/// The data type of the issue field.
		/// </summary>
		public IssueFieldDataType DataType { get; set; }

		/// <summary>
		/// The options for the issue field if applicable.
		/// </summary>
		public List<IssueFieldSingleSelectOptionInput> Options { get; set; }

		/// <summary>
		/// The visibility of the issue field.
		/// </summary>
		public IssueFieldVisibility? Visibility { get; set; }
	}
}
