// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of DeleteProjectV2StatusUpdate
	/// </summary>
	public class DeleteProjectV2StatusUpdateInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the status update to be removed.
		/// </summary>
		public ID StatusUpdateId { get; set; }
	}
}
