// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

#nullable enable

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of DeleteIssueFieldValue.
	/// </summary>
	public class DeleteIssueFieldValuePayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string? ClientMutationId { get; set; }

		/// <summary>
		/// The issue object.
		/// </summary>
		public Issue? Issue { get; set; }

		/// <summary>
		/// Whether the field value was successfully deleted.
		/// </summary>
		public bool? Success { get; set; }
	}
}
