// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of DeleteRepositoryCustomProperty
	/// </summary>
	public class DeleteRepositoryCustomPropertyInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The global relay id of the custom property to be deleted.
		/// </summary>
		public ID Id { get; set; }
	}
}
