// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of DeleteProjectV2StatusUpdate.
	/// </summary>
	public class DeleteProjectV2StatusUpdatePayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the deleted status update.
		/// </summary>
		public ID? DeletedStatusUpdateId { get; set; }

		/// <summary>
		/// The project the deleted status update was in.
		/// </summary>
		public ProjectV2 ProjectV2 { get; set; }
	}
}
