// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

#nullable enable

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of DeleteIssueType.
	/// </summary>
	public class DeleteIssueTypePayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string? ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the deleted issue type
		/// </summary>
		public ID? DeletedIssueTypeId { get; set; }
	}
}
