// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

#nullable enable

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of InviteEnterpriseMember.
	/// </summary>
	public class InviteEnterpriseMemberPayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string? ClientMutationId { get; set; }

		/// <summary>
		/// The created enterprise member invitation.
		/// </summary>
		public EnterpriseMemberInvitation? Invitation { get; set; }
	}
}
