// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of PromoteRepositoryCustomProperty
	/// </summary>
	public class PromoteRepositoryCustomPropertyInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the repository custom property to be promoted.
		/// </summary>
		public ID RepositoryCustomPropertyId { get; set; }
	}
}
