// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

#nullable enable

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of PromoteRepositoryCustomProperty.
	/// </summary>
	public class PromoteRepositoryCustomPropertyPayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string? ClientMutationId { get; set; }

		/// <summary>
		/// The repository custom property that has been promoted.
		/// </summary>
		public RepositoryCustomProperty? RepositoryCustomProperty { get; set; }
	}
}
