// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

#nullable enable

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of RemoveBlockedBy.
	/// </summary>
	public class RemoveBlockedByPayload
	{
		/// <summary>
		/// The previously blocking issue.
		/// </summary>
		public Issue? BlockingIssue { get; set; }

		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string? ClientMutationId { get; set; }

		/// <summary>
		/// The previously blocked issue.
		/// </summary>
		public Issue? Issue { get; set; }
	}
}
