// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

#nullable enable

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of RemoveBlockedBy
	/// </summary>
	public class RemoveBlockedByInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string? ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the blocked issue.
		/// </summary>
		public ID IssueId { get; set; }

		/// <summary>
		/// The ID of the blocking issue.
		/// </summary>
		public ID BlockingIssueId { get; set; }
	}
}
