// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

#nullable enable

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of ReprioritizeSubIssue
	/// </summary>
	public class ReprioritizeSubIssueInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string? ClientMutationId { get; set; }

		/// <summary>
		/// The id of the parent issue.
		/// </summary>
		public ID IssueId { get; set; }

		/// <summary>
		/// The id of the sub-issue to reprioritize.
		/// </summary>
		public ID SubIssueId { get; set; }

		/// <summary>
		/// The id of the sub-issue to be prioritized after (either positional argument after OR before should be specified).
		/// </summary>
		public ID? AfterId { get; set; }

		/// <summary>
		/// The id of the sub-issue to be prioritized before (either positional argument after OR before should be specified).
		/// </summary>
		public ID? BeforeId { get; set; }
	}
}
