// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of ReprioritizeSubIssue.
	/// </summary>
	public class ReprioritizeSubIssuePayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The parent issue that the sub-issue was reprioritized in.
		/// </summary>
		public Issue Issue { get; set; }
	}
}
