// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of RequestReviewsByLogin
	/// </summary>
	public class RequestReviewsByLoginInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The Node ID of the pull request to modify.
		/// </summary>
		public ID PullRequestId { get; set; }

		/// <summary>
		/// The login strings of the users to request reviews from.
		/// </summary>
		public List<string> UserLogins { get; set; }

		/// <summary>
		/// The logins of the bots to request reviews from, including the [bot] suffix (e.g., 'copilot-pull-request-reviewer[bot]').
		/// </summary>
		public List<string> BotLogins { get; set; }

		/// <summary>
		/// The slugs of the teams to request reviews from (format: 'org/team-slug').
		/// </summary>
		public List<string> TeamSlugs { get; set; }

		/// <summary>
		/// Add users to the set rather than replace.
		/// </summary>
		public bool? Union { get; set; }
	}
}
