// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

#nullable enable

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of SetIssueFieldValue.
	/// </summary>
	public class SetIssueFieldValuePayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string? ClientMutationId { get; set; }

		/// <summary>
		/// The issue where the field values were set.
		/// </summary>
		public Issue? Issue { get; set; }

		/// <summary>
		/// The issue field values that were created or updated.
		/// </summary>
		public List<IssueFieldValue>? IssueFieldValues { get; set; }
	}
}
