// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

#nullable enable

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of SetIssueFieldValue
	/// </summary>
	public class SetIssueFieldValueInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string? ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the Issue to set the field value on.
		/// </summary>
		public ID IssueId { get; set; }

		/// <summary>
		/// The issue fields to set on the issue
		/// </summary>
		public List<IssueFieldCreateOrUpdateInput> IssueFields { get; set; } = default!;
	}
}
