// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

#nullable enable

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of UnpinIssueComment
	/// </summary>
	public class UnpinIssueCommentInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string? ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the Issue Comment to unpin. Comment pinning is not supported on Pull Requests.
		/// </summary>
		public ID IssueCommentId { get; set; }
	}
}
