// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

#nullable enable

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of UnpinIssueComment.
	/// </summary>
	public class UnpinIssueCommentPayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string? ClientMutationId { get; set; }

		/// <summary>
		/// The Issue Comment that was unpinned
		/// </summary>
		public IssueComment? IssueComment { get; set; }
	}
}
