// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of UpdateIssueFieldValue
	/// </summary>
	public class UpdateIssueFieldValueInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the issue.
		/// </summary>
		public ID IssueId { get; set; }

		/// <summary>
		/// The field value to update.
		/// </summary>
		public IssueFieldCreateOrUpdateInput IssueField { get; set; }
	}
}
