// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of UpdateIssueType
	/// </summary>
	public class UpdateIssueTypeInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the issue type to update
		/// </summary>
		public ID IssueTypeId { get; set; }

		/// <summary>
		/// Whether or not the issue type is enabled for the organization
		/// </summary>
		public bool? IsEnabled { get; set; }

		/// <summary>
		/// The name of the issue type
		/// </summary>
		public string Name { get; set; }

		/// <summary>
		/// The description of the issue type
		/// </summary>
		public string Description { get; set; }

		/// <summary>
		/// Color for the issue type
		/// </summary>
		public IssueTypeColor? Color { get; set; }
	}
}
