// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

#nullable enable

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of UpdateRepositoryCustomProperty
	/// </summary>
	public class UpdateRepositoryCustomPropertyInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string? ClientMutationId { get; set; }

		/// <summary>
		/// The updated description of the custom property.
		/// </summary>
		public string? Description { get; set; }

		/// <summary>
		/// The updated allowed values for the custom property.
		/// </summary>
		public List<string>? AllowedValues { get; set; }

		/// <summary>
		/// Whether the updated custom property is required.
		/// </summary>
		public bool? Required { get; set; }

		/// <summary>
		/// The updated default value for the custom property if the property is required.
		/// </summary>
		public string? DefaultValue { get; set; }

		/// <summary>
		/// The regex pattern that the value of the custom property must match, if the `value_type` is `string`.
		/// </summary>
		public string? Regex { get; set; }

		/// <summary>
		/// The global relay id of the source of the custom property.
		/// </summary>
		public ID RepositoryCustomPropertyId { get; set; }

		/// <summary>
		/// The updated actors who can edit the values of the custom property.
		/// </summary>
		public RepositoryCustomPropertyValuesEditableBy? ValuesEditableBy { get; set; }

		/// <summary>
		/// Whether this repository custom property requires explicit values.
		/// </summary>
		public bool? RequireExplicitValues { get; set; }
	}
}
