// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

#nullable enable

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of UpdateEnterpriseTwoFactorAuthenticationDisallowedMethodsSetting
	/// </summary>
	public class UpdateEnterpriseTwoFactorAuthenticationDisallowedMethodsSettingInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string? ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the enterprise on which to set the two-factor authentication disallowed methods setting.
		/// </summary>
		public ID EnterpriseId { get; set; }

		/// <summary>
		/// The value for the two-factor authentication disallowed methods setting on the enterprise.
		/// </summary>
		public EnterpriseDisallowedMethodsSettingValue SettingValue { get; set; }
	}
}
