// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of UpdateIssueIssueType
	/// </summary>
	public class UpdateIssueIssueTypeInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the issue type to update on the issue
		/// </summary>
		public ID? IssueTypeId { get; set; }

		/// <summary>
		/// The ID of the issue to update
		/// </summary>
		public ID IssueId { get; set; }
	}
}
