// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

#nullable enable

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of UpdateRepositoryCustomProperty.
	/// </summary>
	public class UpdateRepositoryCustomPropertyPayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string? ClientMutationId { get; set; }

		/// <summary>
		/// The updated repository custom property.
		/// </summary>
		public RepositoryCustomProperty? RepositoryCustomProperty { get; set; }
	}
}
