// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

#nullable enable

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of UpdateIpAllowListUserLevelEnforcementEnabledSetting
	/// </summary>
	public class UpdateIpAllowListUserLevelEnforcementEnabledSettingInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string? ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the owner.
		/// </summary>
		public ID OwnerId { get; set; }

		/// <summary>
		/// The value for the IP allow list user-level enforcement enabled setting.
		/// </summary>
		public IpAllowListUserLevelEnforcementEnabledSettingValue SettingValue { get; set; }
	}
}
